### PR TITLE
Fix for import errors on Windows

### PR DESCRIPTION
**Pull request by Jfeatherstone**
Per Issue #3, I believe I have fixed the import issues that several people were experiencing, and also included slightly more verbose installation instructions on Windows machines. Changes include:

1. I changed the imports of the compiled libraries to be local, as suggested by @GCBallesteros, eg:
 `from _readTTTRRecords_HHT2_HH2 import ffi, lib -> from ._readTTTRRecords_HHT2_HH2 import ffi, lib`

2. I made sure `.pyd` files are included in the `package-data` installation flag, since this is the format that Visual Studio compiles as (at least on my machine). The installation process now properly copies over the importable binaries on both Windows and Linux (I am not able to test Mac, may need to add another file type, possibly `.dylib`) to the installation directory.

3. Wrote out specific instructions on how to install the required modules for Visual Studio on Windows. I have also specified that the package should be installed with `python setup.py install`, which might conflict with what @raphaelproux said in the thread for Issue #3. When I use `pip install .` as suggested, the c files don't compile; I am not sure why this is the case, but running the setup script manually seems to work fine (and the installation can still be managed with pip as usual).

### CODE REVIEW

**Comment by raphaelproux** [comment]
The changes seem to be effective. Thanks for your contribution!

**Comment by GCBallesteros** [comment]
Time as good as any other for a shameless plug. I've spent some time reimplementing the whole new thing [https://github.com/GCBallesteros/trattoria](trattoria)🍕. This time through the library is available on pypi and the libraries are precompiled for all major OS. A `pip install trattoria` on a fresh python environment should be enough if you want to give it a try. It also implements more algorithms and more file formats.

**Comment by raphaelproux** [comment]
> Time as good as any other for a shameless plug. I've spent some time reimplementing the whole new thing [https://github.com/GCBallesteros/trattoria](trattoria)🍕. This time through the library is available on pypi and the libraries are precompiled for all major OS. A `pip install trattoria` on a fresh python environment should be enough if you want to give it a try. It also implements more algorithms and more file formats.

It is amazing! This seems to supersede the readPTU package in every way. Should we consider making readPTU obsolete? We can put a link to Trattoria

**Comment by GCBallesteros** [comment]
I'll ask BG first to make sure he is happy with that.

**Pull request merged**
